export const projects = [
      {
        title: "~/Projeto 1",
        imgClass: "project1",
        describe:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi inventore accusamus veniam dolores quo temporibus ratione quae innulla eos nesciunt similique minima quod aut cum recusandae eaque,autem sit? Lorem ipsum dolor sit amet consectetur adipisicing elit.Quasi inventore accusamus veniam dolores quo temporibus ratione quaein nulla eos nesciunt similique minima quod aut cum recusandaeeaque, autem sit? Lorem ipsum dolor sit amet consectetur adipisicingelit. Quasi inventore accusamus veniam dolores quo temporibusratione quae in nulla eos nesciunt similique minima quod aut cumrecusandae eaque, autem sit? Lorem ipsum dolor sit amet consecteturadipisicing elit. Quasi inventore accusamus veniam dolores quotemporibus ratione quae in nulla eos nesciunt similique minima quodaut cum recusandae eaque, autem sit?",
      },
      {
        title: "~/Projeto 2",
        imgClass: "project2",
        describe:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi inventore accusamus veniam dolores quo temporibus ratione quae innulla eos nesciunt similique minima quod aut cum recusandae eaque,autem sit? Lorem ipsum dolor sit amet consectetur adipisicing elit.Quasi inventore accusamus veniam dolores quo temporibus ratione quaein nulla eos nesciunt similique minima quod aut cum recusandaeeaque, autem sit? Lorem ipsum dolor sit amet consectetur adipisicingelit. Quasi inventore accusamus veniam dolores quo temporibusratione quae in nulla eos nesciunt similique minima quod aut cumrecusandae eaque, autem sit? Lorem ipsum dolor sit amet consecteturadipisicing elit. Quasi inventore accusamus veniam dolores quotemporibus ratione quae in nulla eos nesciunt similique minima quodaut cum recusandae eaque, autem sit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi inventore accusamus veniam dolores quo temporibus ratione quae innulla eos nesciunt similique minima quod aut cum recusandae eaque,autem sit? Lorem ipsum dolor sit amet consectetur adipisicing elit.Quasi inventore accusamus veniam dolores quo temporibus ratione quaein nulla eos nesciunt similique minima quod aut cum recusandaeeaque, autem sit? Lorem ipsum dolor sit amet consectetur adipisicingelit. Quasi inventore accusamus veniam dolores quo temporibusratione quae in nulla eos nesciunt similique minima quod aut cumrecusandae eaque, autem sit? Lorem ipsum dolor sit amet consecteturadipisicing elit. Quasi inventore accusamus veniam dolores quotemporibus ratione quae in nulla eos nesciunt similique minima quodaut cum recusandae eaque, autem sit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi inventore accusamus veniam dolores quo temporibus ratione quae innulla eos nesciunt similique minima quod aut cum recusandae eaque,autem sit? Lorem ipsum dolor sit amet consectetur adipisicing elit.Quasi inventore accusamus veniam dolores quo temporibus ratione quaein nulla eos nesciunt similique minima quod aut cum recusandaeeaque, autem sit? Lorem ipsum dolor sit amet consectetur adipisicingelit. Quasi inventore accusamus veniam dolores quo temporibusratione quae in nulla eos nesciunt similique minima quod aut cumrecusandae eaque, autem sit? Lorem ipsum dolor sit amet consecteturadipisicing elit. Quasi inventore accusamus veniam dolores quotemporibus ratione quae in nulla eos nesciunt similique minima quodaut cum recusandae eaque, autem sit?",
      },
      {
        title: "~/Projeto 3",
        imgClass: "project3",
        describe:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi inventore accusamus veniam dolores quo temporibus ratione quae innulla eos nesciunt similique minima quod aut cum recusandae eaque,autem sit? Lorem ipsum dolor sit amet consectetur adipisicing elit.Quasi inventore accusamus veniam dolores quo temporibus ratione quaein nulla eos nesciunt similique minima quod aut cum recusandaeeaque, autem sit? Lorem ipsum dolor sit amet consectetur adipisicingelit.",
      },
    ];